AWSTemplateFormatVersion: 2010-09-09
Description: "Created by Prashant using CloudFormation"
Resources: 
  myVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      Tags:
        - Key: Env
          Value: Prod
  
  pvtsbt01:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: us-west-1a
      VpcId: 
        Ref:  myVPC
      CidrBlock: 10.0.0.0/24
      Tags:
        - Key: Type
          Value: Private

  pubsbt01:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: us-west-1a
      VpcId:
        Ref:  myVPC
      CidrBlock: 10.0.1.0/24
      Tags:
        - Key: Type
          Value: Public
